### ISSUE TITLE
Getting Server Error (500) while trying to upload

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA-Resources#308]
Since yesterday, i can't upload anything to resource site. Trying to do so gives Server Error (500). SoScared confirmed on discord that he can't upload either, so it is not a problem at me.

**Comment by Baxxster** [comment]
I don't have any map available, could you try to upload now? I've restarted the service and looking at the logs

**Comment by MustaphaTR** [comment]
Still giving Server Error.

**Comment by Baxxster** [comment]
Thanks, I'm getting errors in the log now, it's permission issues, maybe @pchote changed something on the resource yesterday, think it's related to pathing issues

**Comment by Baxxster** [comment]
ERROR:django.request:Internal Server Error: /upload/map/
Traceback (most recent call last):
  File "/home/resource/Envs/resource.openra.net/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/resource/Envs/resource.openra.net/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/resource/sites/resource.openra.net/www/openra/views.py", line 873, in uploadMap
    error_response = uploadingMap.ProcessUploading(user_id, request.FILES['file'], request.POST, rev, previous_rev)
  File "/home/resource/sites/resource.openra.net/www/openra/handlers.py", line 55, in ProcessUploading
    with open(tempname, 'wb+') as destination:
PermissionError: [Errno 13] Permission denied: '/tmp/openramap.oramap'

**Comment by MustaphaTR** [comment]
It is working now.

**Comment by Baxxster** [comment]
I removed the file that locked it down, It's just a temp solutiuon until this get's sorted, will break if two people upload simultaneously for now
